# Generated by Django 3.2.13 on 2022-05-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widget',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='widget',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
