# Generated by Django 3.2.13 on 2022-05-23 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='default_basemap_layer',
            field=models.ForeignKey(blank=True, help_text='If this is empty, the default will be latest basemap', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_default_basemap_layer', to='gap_data.basemaplayer'),
        ),
    ]
