# Generated by Django 3.2.13 on 2022-05-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widget',
            old_name='reference_layer',
            new_name='indicator',
        ),
        migrations.AlterField(
            model_name='widget',
            name='layer_used',
            field=models.CharField(choices=[('Indicator', 'Indicator')], default='Indicator', max_length=256),
        ),
    ]
