# Generated by Django 3.2.13 on 2022-05-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0002_auto_20220520_0349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ('group__name', 'name')},
        ),
        migrations.AddField(
            model_name='dashboard',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icons'),
        ),
    ]
