# Generated by Django 3.2.13 on 2022-05-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0002_auto_20220524_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='operation',
            field=models.CharField(default='Sum', max_length=256),
        ),
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.CharField(default='SummaryWidget', max_length=256),
        ),
    ]
