# Generated by Django 3.2.13 on 2022-05-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0002_dashboard_default_basemap_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemaplayer',
            name='dashboard_default',
            field=models.BooleanField(default=False, help_text='Is the basemap used as default on dashboard editor.'),
        ),
    ]
