# Generated by Django 3.2.13 on 2022-06-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0003_auto_20220525_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='filters',
            field=models.TextField(blank=True, null=True),
        ),
    ]
