# Generated by Django 3.2.8 on 2022-01-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0016_auto_20220106_0750'),
    ]

    operations = [
    ]
