# Generated by Django 3.2.13 on 2022-05-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0033_alter_instancecategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextlayer',
            name='layer_type',
            field=models.CharField(choices=[('ARCGIS', 'ARCGIS'), ('Geojson', 'Geojson'), ('Raster Tile', 'Raster Tile')], default='ARCGIS', max_length=256),
        ),
    ]
