# Generated by Django 3.2.13 on 2022-05-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0034_alter_contextlayer_layer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='source',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
