# Generated by Django 3.2.13 on 2022-05-19 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0037_auto_20220519_0116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contextlayer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contextlayergroup',
            options={},
        ),
        migrations.RemoveField(
            model_name='contextlayer',
            name='enable_by_default',
        ),
        migrations.RemoveField(
            model_name='contextlayer',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='contextlayer',
            name='order',
        ),
        migrations.RemoveField(
            model_name='contextlayer',
            name='show_on_map',
        ),
        migrations.RemoveField(
            model_name='contextlayergroup',
            name='order',
        ),
        migrations.DeleteModel(
            name='ContextLayerParameter',
        ),
    ]
