# Generated by Django 3.2.13 on 2022-05-19 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0038_auto_20220519_0159'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programinstance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='programinstance',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='programinstance',
            name='program',
        ),
        migrations.AlterUniqueTogether(
            name='programintervention',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='program_instance',
        ),
        migrations.RemoveField(
            model_name='programintervention',
            name='scenario_level',
        ),
        migrations.RemoveField(
            model_name='scenariolevel',
            name='instance',
        ),
        migrations.AlterUniqueTogether(
            name='indicatorscenariorule',
            unique_together={('indicator', 'name')},
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='ProgramInstance',
        ),
        migrations.DeleteModel(
            name='ProgramIntervention',
        ),
        migrations.RemoveField(
            model_name='indicatorscenariorule',
            name='scenario_level',
        ),
        migrations.DeleteModel(
            name='ScenarioLevel',
        ),
    ]
