# Generated by Django 3.2.13 on 2022-05-19 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0039_auto_20220519_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geometryuploaderfile',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='geometryuploaderlog',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='point_of_interests',
        ),
        migrations.RemoveField(
            model_name='geometry',
            name='active_date_from',
        ),
        migrations.RemoveField(
            model_name='geometry',
            name='active_date_to',
        ),
        migrations.RemoveField(
            model_name='geometry',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='geometry',
            name='dashboard_link',
        ),
        migrations.RemoveField(
            model_name='geometry',
            name='instance',
        ),
        migrations.DeleteModel(
            name='GeometryLevelInstance',
        ),
        migrations.DeleteModel(
            name='GeometryUploader',
        ),
        migrations.DeleteModel(
            name='GeometryUploaderFile',
        ),
        migrations.DeleteModel(
            name='GeometryUploaderLog',
        ),
    ]
