# Generated by Django 3.2.13 on 2022-05-19 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0040_auto_20220519_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorgroup',
            name='instance',
        ),
        migrations.DeleteModel(
            name='Instance',
        ),
        migrations.DeleteModel(
            name='InstanceCategory',
        ),
    ]
