# Generated by Django 3.2.13 on 2022-05-19 04:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0041_auto_20220519_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source', models.CharField(max_length=512)),
                ('last_update', models.DateField(default=datetime.datetime.today)),
                ('geometries', models.ManyToManyField(blank=True, null=True, to='gap_data.Geometry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenceLayerLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('reference_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap_data.referencelayer')),
            ],
            options={
                'unique_together': {('reference_layer', 'level')},
            },
        ),
    ]
