# Generated by Django 3.2.13 on 2022-05-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0042_referencelayer_referencelayerlevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={},
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='access_level',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='order',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='show_in_context_analysis',
        ),
    ]
