# Generated by Django 3.2.13 on 2022-05-19 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0043_auto_20220519_0549'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndicatorScenarioRule',
            new_name='IndicatorRule',
        ),
    ]
