# Generated by Django 3.2.13 on 2022-05-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0044_rename_indicatorscenariorule_indicatorrule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plugin',
            new_name='Widget',
        ),
        migrations.RemoveField(
            model_name='indicatorvalueextradetailrow',
            name='indicator_value',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='geometry_reporting_units',
        ),
        migrations.AddField(
            model_name='indicator',
            name='reporting_level',
            field=models.CharField(default='District', max_length=64),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='geom_identifier',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorrule',
            name='color',
            field=models.CharField(blank=True, help_text='Color of the rule', max_length=16, null=True),
        ),
        migrations.DeleteModel(
            name='IndicatorValueExtraDetailColumn',
        ),
        migrations.DeleteModel(
            name='IndicatorValueExtraDetailRow',
        ),
    ]
