# Generated by Django 3.2.8 on 2022-04-22 03:05

from django.db import migrations


def assign_data(apps, schema_editor):
    Indicator = apps.get_model('gap_data', 'Indicator')
    IndicatorValue = apps.get_model('gap_data', 'IndicatorValue')

    for indicator in Indicator.objects.all():
        if indicator.geometry_reporting_level:
            indicator.reporting_level = indicator.geometry_reporting_level.name
            indicator.save()
    for val in IndicatorValue.objects.all():
        if val.geometry:
            val.geom_identifier = val.geometry.identifier
            val.save()


class Migration(migrations.Migration):
    dependencies = [
        ('gap_data', '0045_auto_20220519_0805'),
    ]

    operations = [
        migrations.RunPython(assign_data)]
