# Generated by Django 3.2.13 on 2022-05-19 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0046_assing_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='reference_layers',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='reference_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gap_data.referencelayer'),
        ),
        migrations.AlterField(
            model_name='referencelayer',
            name='geometries',
            field=models.ManyToManyField(blank=True, to='gap_data.Geometry'),
        ),
    ]
