# Generated by Django 3.2.13 on 2022-05-19 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0047_auto_20220519_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='geometry_reporting_level',
        ),
        migrations.AlterUniqueTogether(
            name='indicatorvalue',
            unique_together={('indicator', 'date', 'geom_identifier')},
        ),
        migrations.RemoveField(
            model_name='indicatorvalue',
            name='geometry',
        ),
    ]
