# Generated by Django 3.2.13 on 2022-05-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0048_auto_20220519_0823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReferenceLayerLevel',
        ),
    ]
