# Generated by Django 3.2.13 on 2022-05-19 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0049_delete_referencelayerlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceLayerLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('level_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap_data.geometrylevelname')),
                ('reference_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap_data.referencelayer')),
            ],
            options={
                'unique_together': {('reference_layer', 'level')},
            },
        ),
    ]
