# Generated by Django 3.2.13 on 2022-05-20 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0051_dashboard_indicator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='Indicator',
            new_name='Indicators',
        ),
    ]
