# Generated by Django 3.2.13 on 2022-05-20 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gap_data', '0052_rename_indicator_dashboard_indicators'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='Indicators',
            new_name='indicators',
        ),
    ]
