# Generated by Django 3.2.13 on 2022-06-20 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextlayergroup',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geosight_data.contextlayergroup'),
        ),
    ]
