# Generated by Django 3.2.13 on 2022-06-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0002_contextlayergroup_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='reference_layer',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='reference_layer_identifier',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
