# Generated by Django 3.2.13 on 2022-07-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0006_indicatorvalueextradetailcolumn_indicatorvalueextradetailrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='reporting_level',
            field=models.CharField(help_text='Indicate what level of the data for this indicator. It can use level name or level number.', max_length=64),
        ),
    ]
