# Generated by Django 3.2.13 on 2022-07-11 04:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0010_auto_20220711_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
