# Generated by Django 3.2.13 on 2022-06-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='georepo_api_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='georepo_url',
            field=models.CharField(default='https://staging.georepo.kartoza.com/', max_length=512),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='primary_color',
            field=models.CharField(default='#1CABE2', help_text='Theme color for the website. Put the hex color with # (e.g. #ffffff) or put the text of color. (e.g. blue)', max_length=16),
        ),
    ]
