# Generated by Django 3.2.13 on 2022-06-27 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220621_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePreferencesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='settings/images')),
                ('title', models.CharField(blank=True, help_text='Title of image.', max_length=256, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of image.', null=True)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sitepreferences')),
            ],
        ),
    ]
