# Generated by Django 3.2.13 on 2022-07-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitepreferencesimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='anti_primary_color',
            field=models.CharField(default='#FFFFFF', help_text='Anti of primary color that used for text in primary color.', max_length=16),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='anti_secondary_color',
            field=models.CharField(default='#FFFFFF', help_text='Anti of secondary color that used for text in primary color.', max_length=16),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='anti_tertiary_color',
            field=models.CharField(default='#FFFFFF', help_text='Anti of tertiary color that used for text in primary color.', max_length=16),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='secondary_color',
            field=models.CharField(default='#374EA2', help_text='Secondary color that used for example for button. ', max_length=16),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='tertiary_color',
            field=models.CharField(default='#297CC2', help_text='Tertiary color that used for example for some special place. ', max_length=16),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='primary_color',
            field=models.CharField(default='#1CABE2', help_text='Main color for the website. Put the hex color with # (e.g. #ffffff) or put the text of color. (e.g. blue)', max_length=16),
        ),
    ]
